### ISSUE TITLE
Add fonk options

### ISSUE THREAD

**Issue by thijsmie** [thijsmie/fonk#1]
```toml
[tool.fonk]
options = [
   { name = "sources", shorthand = "f", type = "list[Path]", default = ["src"] },
]

[tool.fonk.commands.ruff]
type = "uvx"
arguments = ["ruff", "format", "$sources"]
```
